name: Validate GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  actionlint:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    name: gh-action-lint
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

# yamllint disable rule:line-length
      - name: Install actionlint
        run: |
          curl -sSL https://github.com/rhysd/actionlint/releases/download/v1.7.7/actionlint_1.7.7_linux_amd64.tar.gz | tar -xz
          sudo mv actionlint /usr/local/bin/

      - name: Check workflow files
        run: actionlint -color
